// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADqfy4XlPtUqyoC0Kj0V3dxEDeoZd9BU',
    appId: '1:1050249073483:web:0adf58d6b99374f8324ece',
    messagingSenderId: '1050249073483',
    projectId: 'flutter-sample-2023119',
    authDomain: 'flutter-sample-2023119.firebaseapp.com',
    storageBucket: 'flutter-sample-2023119.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5cfpiSpEku_UUDeU5-m1XEgasRmNjKrg',
    appId: '1:1050249073483:android:225c51873104c0a4324ece',
    messagingSenderId: '1050249073483',
    projectId: 'flutter-sample-2023119',
    storageBucket: 'flutter-sample-2023119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tQMxOLVleVy0qk0FzKPcyGMiT2q5y5k',
    appId: '1:1050249073483:ios:3e97e7c0dec614f2324ece',
    messagingSenderId: '1050249073483',
    projectId: 'flutter-sample-2023119',
    storageBucket: 'flutter-sample-2023119.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tQMxOLVleVy0qk0FzKPcyGMiT2q5y5k',
    appId: '1:1050249073483:ios:d637b555dcc9bf51324ece',
    messagingSenderId: '1050249073483',
    projectId: 'flutter-sample-2023119',
    storageBucket: 'flutter-sample-2023119.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
